# Site settings
title: COMPILADORES
year: 2016
slack_page: https://cc4-2016.slack.com
footerlogo: logo-footer.png
descripcion: >
 Pagina del curso CC4 - Compiladores de Universidad Galileo
baseurl: ""
url: "https://cc-4.github.io/"

# Build settings
markdown: kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
