title: COMPILADORES
slack_page: https://cc4-2016.slack.com/
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cc-4.github.io/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
